import { Language } from "@/types/statement";

export const UI_TEXT = {
  en: {
    appTitle: "ChowBus Statement Analyzer",
    appSubtitle: "Upload your monthly POS statement for an instant summary",
    uploadTitle: "Upload Your Statement",
    uploadDesc: "Drag and drop your ChowBus PDF statement here, or click to browse",
    uploadHint: "Supports PDF files up to 20MB",
    browseButton: "Browse Files",
    fileReady: "File ready to analyze",
    analyzeButton: "Analyze Statement",
    loading: "Analyzing your statement…",
    loadingSubtext: "Claude AI is reading your PDF. This takes 5–15 seconds.",
    summaryTitle: "Monthly Statement Summary",
    keyInsights: "Key Insights",
    uploadAnother: "Upload Another Statement",
    printSummary: "Print Summary",
    errorTitle: "Analysis Failed",
    errorRetry: "Try Again",
    generatedBy: "Generated by ChowBus Statement Analyzer",
    pageOf: "Page",
    of: "of",
    // Order breakdown
    orderBreakdownTitle: "Order Breakdown by Channel",
    colChannel: "Channel",
    colOrders: "Orders",
    colRevenue: "Revenue",
    colTips: "Tips",
    // Privacy
    privacyNotice: "Your privacy is protected",
    privacyDetail: "Your PDF is sent directly to Claude AI for analysis and is never stored on our servers. No data, no cookies, no history — everything is erased the moment you leave or refresh this page.",
    // Chat
    chatTitle: "Ask about your statement",
    chatPlaceholder: "Ask a question...",
    chatSend: "Send",
    chatWelcome: "I can answer any questions about your uploaded statement. Try asking about specific line items, trends, or comparisons.",
    chatError: "Something went wrong. Please try again.",
  },
  zh: {
    appTitle: "ChowBus 月报分析器",
    appSubtitle: "上传您的月度POS报表，即刻获得摘要",
    uploadTitle: "上传您的报表",
    uploadDesc: "将ChowBus PDF报表拖放到此处，或点击浏览",
    uploadHint: "支持最大20MB的PDF文件",
    browseButton: "浏览文件",
    fileReady: "文件已准备好分析",
    analyzeButton: "分析报表",
    loading: "正在分析您的报表…",
    loadingSubtext: "Claude AI 正在读取您的PDF，这需要5-15秒。",
    summaryTitle: "月度报表摘要",
    keyInsights: "关键洞察",
    uploadAnother: "上传其他报表",
    printSummary: "打印摘要",
    errorTitle: "分析失败",
    errorRetry: "重试",
    generatedBy: "由 ChowBus 月报分析器生成",
    pageOf: "第",
    of: "页，共",
    // Order breakdown
    orderBreakdownTitle: "按渠道订单明细",
    colChannel: "渠道",
    colOrders: "订单数",
    colRevenue: "营业额",
    colTips: "小费",
    // Privacy
    privacyNotice: "您的隐私受到保护",
    privacyDetail: "您的PDF直接发送给Claude AI进行分析，从不存储在我们的服务器上。无数据、无Cookie、无历史记录——您离开或刷新页面后，所有内容立即清除。",
    // Chat
    chatTitle: "询问您的报表",
    chatPlaceholder: "提问...",
    chatSend: "发送",
    chatWelcome: "我可以回答关于您上传报表的任何问题。试试询问具体项目、趋势或对比分析。",
    chatError: "出了点问题，请重试。",
  },
  es: {
    appTitle: "Analizador de Estados ChowBus",
    appSubtitle: "Sube tu estado mensual de POS para un resumen instantáneo",
    uploadTitle: "Sube Tu Estado",
    uploadDesc: "Arrastra y suelta tu PDF de ChowBus aquí, o haz clic para buscar",
    uploadHint: "Admite archivos PDF de hasta 20MB",
    browseButton: "Buscar Archivos",
    fileReady: "Archivo listo para analizar",
    analyzeButton: "Analizar Estado",
    loading: "Analizando tu estado…",
    loadingSubtext: "Claude AI está leyendo tu PDF. Esto toma 5–15 segundos.",
    summaryTitle: "Resumen del Estado Mensual",
    keyInsights: "Perspectivas Clave",
    uploadAnother: "Subir Otro Estado",
    printSummary: "Imprimir Resumen",
    errorTitle: "Análisis Fallido",
    errorRetry: "Intentar de Nuevo",
    generatedBy: "Generado por ChowBus Statement Analyzer",
    pageOf: "Página",
    of: "de",
    // Order breakdown
    orderBreakdownTitle: "Desglose de Pedidos por Canal",
    colChannel: "Canal",
    colOrders: "Pedidos",
    colRevenue: "Ingresos",
    colTips: "Propinas",
    // Privacy
    privacyNotice: "Tu privacidad está protegida",
    privacyDetail: "Tu PDF se envía directamente a Claude AI para su análisis y nunca se almacena en nuestros servidores. Sin datos, sin cookies, sin historial: todo se borra en el momento en que abandonas o recargas esta página.",
    // Chat
    chatTitle: "Pregunta sobre tu estado",
    chatPlaceholder: "Haz una pregunta...",
    chatSend: "Enviar",
    chatWelcome: "Puedo responder cualquier pregunta sobre tu estado de cuenta. Prueba preguntar sobre partidas específicas, tendencias o comparaciones.",
    chatError: "Algo salió mal. Por favor, inténtalo de nuevo.",
  },
} as const;

export function t(lang: Language, key: keyof typeof UI_TEXT.en): string {
  return UI_TEXT[lang][key];
}

export function getLabel(item: { label_en: string; label_zh: string; label_es: string }, lang: Language): string {
  return lang === "zh" ? item.label_zh : lang === "es" ? item.label_es : item.label_en;
}

export function getTitle(section: { title_en: string; title_zh: string; title_es: string }, lang: Language): string {
  return lang === "zh" ? section.title_zh : lang === "es" ? section.title_es : section.title_en;
}

export function getNote(item: { note_en?: string; note_zh?: string; note_es?: string }, lang: Language): string {
  return (lang === "zh" ? item.note_zh : lang === "es" ? item.note_es : item.note_en) || "";
}

export function getInsights(data: { insights_en: string; insights_zh: string; insights_es: string }, lang: Language): string {
  return lang === "zh" ? data.insights_zh : lang === "es" ? data.insights_es : data.insights_en;
}

export function getChannel(row: { channel_en: string; channel_zh: string; channel_es: string }, lang: Language): string {
  return lang === "zh" ? row.channel_zh : lang === "es" ? row.channel_es : row.channel_en;
}
